{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToStartCallback"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":2,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/reachability\/reachabilityerror\/failedtostartcallback(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/Reachability\/documentation\/Reachability\/ReachabilityError\/failedToStartCallback(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An error indicating the reachability callback could not be configured"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToStartCallback"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"title":"ReachabilityError.failedToStartCallback(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:12Reachability0A5ErrorO21failedToStartCallbackyACs5Int32VcACmF","modules":[{"name":"Reachability"}]},"hierarchy":{"paths":[["doc:\/\/Reachability\/documentation\/Reachability","doc:\/\/Reachability\/documentation\/Reachability\/ReachabilityError"]]},"references":{"doc://Reachability/documentation/Reachability/ReachabilityError":{"role":"symbol","title":"ReachabilityError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReachabilityError"}],"abstract":[{"type":"text","text":"Errors that could cause a "},{"type":"codeVoice","code":"ReachabiltiyMonitor"},{"type":"text","text":" to fail"}],"identifier":"doc:\/\/Reachability\/documentation\/Reachability\/ReachabilityError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReachabilityError"}],"url":"\/documentation\/reachability\/reachabilityerror"},"doc://Reachability/documentation/Reachability/ReachabilityError/failedToStartCallback(_:)":{"role":"symbol","title":"ReachabilityError.failedToStartCallback(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToStartCallback"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"An error indicating the reachability callback could not be configured"}],"identifier":"doc:\/\/Reachability\/documentation\/Reachability\/ReachabilityError\/failedToStartCallback(_:)","kind":"symbol","type":"topic","url":"\/documentation\/reachability\/reachabilityerror\/failedtostartcallback(_:)"},"doc://Reachability/documentation/Reachability":{"role":"collection","title":"Reachability","abstract":[{"type":"text","text":"A Swift replacement for SCNetworkReachability with support for structured concurrency."}],"identifier":"doc:\/\/Reachability\/documentation\/Reachability","kind":"symbol","type":"topic","url":"\/documentation\/reachability"}}}